osx_image: xcode9
language: objective-c
xcode_scheme:
  - Bugger
  - BuggerExample
script: "xcodebuild Bugger.xcodeproj -scheme $XCODE_SCHEME -destination 'platform=iOS Simulator,name=iPhone X,OS=latest' build test"
